//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int ID { get; set; }
        public int ClientID { get; set; }
        public int MasterID { get; set; }
        public int ServiceTypeID { get; set; }
        public string DateTime { get; set; }
        public string PaymentMethod { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ServiceType ServiceType { get; set; }
    }
}
