//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatTaken
    {
        public int screening { get; set; }
        public int seat { get; set; }
    
        public virtual Screening Screening1 { get; set; }
    }
}
